--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/buchwasa/UHC
build-by-default: true
branches:
- pm4
projects:
  UHC:
    path: ""
    libs:
      - src: buchwasa/ScoreFactory/ScoreFactory
        branch: pm4
        version: 3.0.1
      - src: thebigsmilexd/customui/customui
        version: ^4.0.0
        branch: PM4
...
